variable "tags" {}
variable "env" {}
variable "name" {}
variable "subnets" {}
variable "vpc_id" {}
variable "allow_alb_cidr" {}
variable "internal" {}
variable "app_port" {}
variable "allow_app_cidr" {}
